### ISSUE TITLE
Missing InitgPty:Id field in the header

### ISSUE THREAD

**Issue by arturoribes** [perrich/sepawriter#8]
Hi,

I am comparing the output of one of your tests with a sample xml file I have and in the header there is a missing field, the initiator party id (Id inside InitgPty). Checking your code, it seems that you have the initiating party Name and Id as string, which is not right. The Id is a struct itself which, for a company,, contains an OrgId field with Id computed using MOD97-10 algorithm. At least this is the case in Spain, where I am using this library.

**Comment by perrich** [comment]
Hi, 

**You've right the initiator party id should be a struct but it is fixed in the library thanks to  @christoforosl** (see GenerateXml() method in SepaCreditTransfer). I think you've not updated your branch.

https://www.iso20022.org/message_archive.page explain that you can have two different cases:

`<Id>
  <OrgId>
    <Othr>
      <Id>...</Id>
    </Othr>
  <OrgId>
</Id>`

or
`<Id>
  <PrvtId>
    <Othr>
      <Id>...</Id>
    </Othr>
  <PrvtId>
</Id>`

Seems that the Id value is a text without any rules:

> 9.1.16
> Identification <Id>
> Presence: [1..1]
> Definition: Identification assigned by an institution.
> Data Type: Max35Text
> Format: maxLength: 35
> minLength: 1

**Comment by arturoribes** [comment]
Now i see the problem. I was looking at the code in SepaDebitTransfer (pain.008.001.02) and in there the InitgPty>Id  does not contain OrgId>Othr>Id, so I guess it is a bug in the code.

**Comment by perrich** [comment]
Yes, thank you. 
The fix was done in the SepaCreditTransfer but not in the SepaDebitTransfer. I've not checked that and it's really a bug!

**Comment by perrich** [comment]
Hope that the last commit fixed the issue.
